### ISSUE TITLE
Add git and version metadata

### ISSUE THREAD

**Issue by popen2** [platzio/chart-ext#1]
Currently git metadata (branch, commit, version) is parsed from the chart tag.

This creates issues when trying to encode long names into tags, for example if branch names contain characters which can't be in a tag (like `/`) or when the resulting tag is too long to be used in labels.

The idea here is to move this metadata into `Chart.yaml` annotations. Usage example:

```yaml
apiVersion: v2
name: ...
version: ...

annotations:
  platz.io/git/commit: f955c983177de6453c276429050957b409997314
  platz.io/git/branch: master
  platz.io/git/repo: https://github.com/a/b
  platz.io/git/provider: github
```

*When present in `Chart.yaml`, the metadata supersedes the chart tag parsing.*

Helm's `version` is used as a Semver version instead of what would have been parsed from the chart tag.

`platz.io/git/branch` allows for upgrades to be suggested when a newer release is detected on the same branch

When `platz.io/git/repo`,`platz.io/git/type` and `platz.io/git/commit` are present, Platz would be able to generate links into the source control provider. When upgrading, Platz would also be able to generate links for diffs, assuming the provider supports it.
